<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\CleanStart.Domain\CleanStart.Domain.csproj" />
	  <ProjectReference Include="..\CleanStart.Service.Abstractions\CleanStart.Service.Abstractions.csproj" />
      <ProjectReference Include="..\..\Shared\CleanStart.Shared\CleanStart.Shared.csproj" />
  </ItemGroup>

</Project>
