<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanStart.Shared\CleanStart.Shared.csproj" />
    <ProjectReference Include="..\..\Infrastructure\CleanStart.Infrastructure.Persistence\CleanStart.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\CleanStart.Infrastructure.Service\CleanStart.Infrastructure.Service.csproj" />
    <ProjectReference Include="..\..\Core\CleanStart.Application\CleanStart.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog.Extensions.Logging" Version="5.5.0" />
  </ItemGroup>

</Project>